/**
* Swagger Petstore - OpenAPI 3.0
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.apiSchema


import kotlinx.serialization.Serializable
/**
 * 
 * @param code HTTP status code
 * @param message Error message
 * @param details Additional error details as string values
 */
@Serializable
data class ErrorResponse(
    /* HTTP status code */
    val code: kotlin.Int,
    /* Error message */
    val message: kotlin.String,
    /* Additional error details as string values */
    val details: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
) 

