/**
* Swagger Petstore - OpenAPI 3.0
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.apiSchema

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

/**
 * APIエラーレスポンス
 * 
 * @param code HTTPステータスコード
 * @param message エラーメッセージ
 * @param details 任意の追加情報
 */
@Serializable
data class ErrorResponse(
    val code: Int,
    val message: String,
    val details: Map<String, String>? = null
)

