/**
* Swagger Petstore - OpenAPI 3.0
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.apiSchema


import kotlinx.serialization.Serializable
/**
 * 
 * @param message 
 * @param timestamp ISO-8601 formatted date-time of the health check execution
 * @param status Overall system health status
 * @param services Status of individual services that were checked
 * @param details Additional status details that vary based on health status
 */
@Serializable
data class HealthcheckMessage(
    val message: kotlin.String,
    /* ISO-8601 formatted date-time of the health check execution */
    val timestamp: kotlin.String,
    /* Overall system health status */
    val status: HealthcheckMessage.Status,
    /* Status of individual services that were checked */
    val services: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null,
    /* Additional status details that vary based on health status */
    val details: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
) 
{
    /**
    * Overall system health status
    * Values: healthy,degraded,unhealthy
    */
    enum class Status(val value: kotlin.String){
        healthy("healthy"),
        degraded("degraded"),
        unhealthy("unhealthy");
    }
}

