/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.apiSchema

import kotlinx.serialization.Serializable


/**
 * 
 * @param message 
 */
@Serializable
data class HealthcheckMessage(
    val message: kotlin.String
) 

