openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 0.0.1
tags:
  - name: healthcheck
    description: Healthcheck endpoint
paths:
  /healthcheck:
    get:
      tags:
        - healthcheck
      summary: Healthcheck endpoint
      operationId: healthcheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthcheckMessage'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: HTTP status code
        message:
          type: string
          description: Error message
        details:
          type: object
          additionalProperties:
            type: string
          description: Additional error details as string values
      required:
        - code
        - message
    HealthcheckMessage:
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
          description: ISO-8601 formatted date-time of the health check execution
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
          description: Overall system health status
        services:
          type: object
          additionalProperties:
            type: boolean
          description: Status of individual services that were checked
        details:
          type: object
          additionalProperties:
            type: string
          description: Additional status details that vary based on health status
      required:
        - message
        - timestamp
        - status