openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 0.0.1
tags:
  - name: healthcheck
    description: Healthcheck endpoint
paths:
  /healthcheck:
    get:
      tags:
        - healthcheck
      summary: Healthcheck endpoint
      operationId: healthcheck2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthcheckMessage'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    HealthcheckMessage:
      type: object
      properties:
        message:
          type: string
      required:
        - message
