/**
* Swagger Petstore - OpenAPI 3.0
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.api

import io.ktor.resources.*
import kotlinx.serialization.*
import com.example.apiSchema.*

    object ApiPaths {
                /**
                    * Healthcheck endpoint
                * 
                */
                    @Serializable @Resource("/healthcheck") class healthcheck

    }
